// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Image$BsFaker = require("bs-faker/src/Image.bs.js");

console.log("Hello World");

var food = Image$BsFaker.food(undefined, undefined, undefined, /* () */0);

var y = Math.PI * 3.0;

var z = 4;

((console.log('food is:', food)));

(( console.log("z is:", z)  ));

var f = (3 ** 2);

var a = 3;

var b = "hello";

var c = true;

var d = 3.14;

exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
exports.food = food;
exports.y = y;
exports.z = z;
exports.f = f;
/*  Not a pure module */
