// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Util$Reasonable = require("./Util.bs.js");

console.log("hello", "io");

var x = 14;

Util$Reasonable.printDir(0, "Demo.re", "./");

console.log("----------------------------------------");

Util$Reasonable.printDir(0, undefined, "./");

var y = 7;

exports.y = y;
exports.x = x;
/*  Not a pure module */
