// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


console.log(5);

var msg = "noice";

console.log(msg);

var a = 3;

var b = /* tuple */[
  4,
  "Hello",
  /* "A" */65,
  true,
  3.14
];

var c = /* record */[
  /* age */5,
  /* name */"Bob"
];

var isThisCool = /* Yes */0;

exports.a = a;
exports.b = b;
exports.c = c;
exports.isThisCool = isThisCool;
exports.msg = msg;
/*  Not a pure module */
