// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var List = require("bs-platform/lib/js/list.js");
var Path = require("path");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function getAbsolutePath(path) {
  return Path.resolve(__dirname, path);
}

function padText(padding, text) {
  return $$String.make(padding, /* " " */32) + text;
}

function printDir(padding, path) {
  var absolutePath = Path.resolve(__dirname, path);
  var options = {
    withFileTypes: true
  };
  return List.iter((function (item) {
                if (item.isDirectory()) {
                  console.log(padText(padding, "📁" + (" " + item.name)));
                  return printDir(padding + 1 | 0, absolutePath + ("/" + item.name));
                } else {
                  console.log(padText(padding, "📄" + (" " + item.name)));
                  return /* () */0;
                }
              }), $$Array.to_list(Fs.readdirSync(absolutePath, options)));
}

exports.getAbsolutePath = getAbsolutePath;
exports.padText = padText;
exports.printDir = printDir;
/* fs Not a pure module */
